### ISSUE TITLE
Error in AzureFunction when creating Entity with Related Entity in Single Request

### ISSUE THREAD

**Issue by zaha** [microsoft/PowerPlatform-CdsServiceClient#20]
Hi everyone,

I have a very strange error happening in one of my Azure Functions (v3) when trying to create a parent Entity record with a couple of child records (1:N relationship):

```
The tv_childentity (Id = 3456ae17-8b9e-ea11-a812-000d3ab6e3d6) in the "tv_parententity_Children." relationship with the tv_parententity (Id = 3356ae17-8b9e-ea11-a812-000d3ab6e3d6) doesn't exist.

   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Create(Entity entity)
   at TeamViewer.D365.Crm.WebApiRepositories.Services.PardonManagementRepository.<CreateAsync>d__3.MoveNext() in D:\Workspace\D365\CRM Web API Repositories\Persistence\Services\PardonManagementRepository.cs:line 51
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TeamViewer.D365.Crm.Pardoning.Functions.CreatePardonManagement.<CreatePardon>d__4.MoveNext() in D:\Workspace\D365\CRM Pardon Management\Presentation\TeamViewer.D365.Crm.Pardoning.Functions\CreatePardonManagement.cs:line 142
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TeamViewer.D365.Crm.Pardoning.Functions.CreatePardonManagement.<Run>d__2.MoveNext() in D:\Workspace\D365\CRM Pardon Management\Presentation\TeamViewer.D365.Crm.Pardoning.Functions\CreatePardonManagement.cs:line 80
```

The weird thing is when I run the exact same code + input data outside of the Azure Function, it is running fine. (As you can see I have a class library with a repository for taking care of creating the entities. Running the repository in an automated test creates the parent + child entities without error.)

I've worked around this for now by first creating the parent record and then bulk creating the child records afterwards, but of course it would be nicer to do everything in one go.

**Comment by MattB-msft** [comment]
did you wire up the logger to see what its complaining about? 
also you can check the LastException on the client to see if it captured it. 

what type of function is this?  Linux or Windows? or?

**Comment by zaha** [comment]
Hi @MattB-msft ,
how do you wire up a logger with the client?

I've checked the client when the error occurs:

`LastCdsError`
```
************ FaultException`1 - Create : Create To CDS via IOrganizationService |=> The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist.
The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist. => The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist.[TerminalFailure] Failed to Execute Command - Create : RequestID=78a2c134-6dda-4e73-a10e-4dd492330d8a : Create To CDS via IOrganizationService duration=00:00:00.4039282 ExceptionMessage = The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist.
```

The `LastCdsException` is exactly the same as the one posted above, just with a shorter StackTrace obviously. I've checked if there is more information hidden somewhere inside the Exception and found this OriginalException:

```
Microsoft.Crm.CrmException: The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist. ---> Microsoft.Crm.CrmException: The tv_pardonrequest (Id = 7e45684f-caa0-ea11-a812-000d3ab6e3d6) in the "tv_pardonmanagement_Requests." relationship with the tv_pardonmanagement (Id = 7d45684f-caa0-ea11-a812-000d3ab6e3d6) doesn't exist.
   at Microsoft.Crm.Extensibility.ExtensiblePlatformMessageDispatcher.HandleRelatedEntities(BusinessEntity primaryEntity, EntityState defaultState, ExecutionContext context)
   at Microsoft.Crm.Extensibility.ExtensiblePlatformMessageDispatcher.CreateWithRelatedEntities(BusinessEntity entity, ExecutionContext context)
   at Microsoft.Crm.Extensibility.ExtensiblePlatformMessageDispatcher.CreateWithInvocationSource(BusinessEntity entity, Int32 invocationSource, ExecutionContext context)
   at Microsoft.Crm.BusinessEntities.BusinessProcessObject.<>c__DisplayClass215_0.<Create>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
   --- End of inner exception stack trace ---
   at Microsoft.Crm.Extensibility.VersionedPluginProxyStepBase.Execute(PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.PipelineInstrumentationHelper.Execute(Boolean instrumentationEnabled, String stopwatchName, ExecuteWithInstrumentation action, PipelineExecutionContext context)
   at Microsoft.Crm.Extensibility.Pipeline.<>c__DisplayClass3_0.<RunStep>b__0()
```
and these values:
```
+		[2]	{[ApiStepKey, {a81bf3fd-91f1-e911-a812-000d3ab719d7}]}	System.Collections.Generic.KeyValuePair<string, object>
+		[3]	{[ApiDepthKey, 1]}	System.Collections.Generic.KeyValuePair<string, object>
+		[4]	{[ApiActivityIdKey, {1b2a4ed2-04f7-4182-8eb4-c60399dc2dd5}]}	System.Collections.Generic.KeyValuePair<string, object>
+		[5]	{[ApiPluginSolutionNameKey, System]}	System.Collections.Generic.KeyValuePair<string, object>
+		[6]	{[ApiStepSolutionNameKey, System]}	System.Collections.Generic.KeyValuePair<string, object>
+		[7]	{[ApiExceptionCategory, ClientError]}	System.Collections.Generic.KeyValuePair<string, object>
+		[8]	{[ApiExceptionMesageName, ObjectDoesNotExist]}	System.Collections.Generic.KeyValuePair<string, object>
+		[9]	{[ApiExceptionHttpStatusCode, 404]}	System.Collections.Generic.KeyValuePair<string, object>
```

This is a .NET Core 3.1 function I'm running on Windows 10 on the local Azure Emulator. The error happens on the Azure instance, too.

**Comment by MattB-msft** [comment]
Thanks, for the info..  Your getting the full error there. 

Based on the error your seeing, that is CDS Saying that a relationship that is required does not exist.. IE the error is coming from the server its not your code.  
I just took a look at the request ID that your error reports in our telemetry and I do not se a custom plugin, thus I'm going to have to suggest that  you have a required lookup that is being populated with a ID that does not exist. 

Could you validate the data?  specifically that there is a record in tv_pardonmanagement with 7d45684f-caa0-ea11-a812-000d3ab6e3d6 that is valid to be linked 

thanks

**Comment by zaha** [comment]
Hi Matt, 

thanks for confirming.

The record with GUID 7d45684f-caa0-ea11-a812-000d3ab6e3d6 does indeed not exist, which is the problem here: I am trying to create both a tv_pardonmanagement (parent) and a couple of tv_pardonrequest (children) records in a single Create request to the CDS. According to the documentation this can be done like so:

```cs
var pardon = new Entity("tv_pardonmanagement");
// Set some attributes coming in via JSON from outside

var childRequests = new EntityCollection { EntityName = "tv_pardonrequest" };
var listValues = value as IEnumerable; // Coming in via JSON from outside

if (listValues == null)
{
	continue;
}

foreach (object request in listValues)
{
	var childEntity = new Entity("tv_pardonrequest");
	// Set some attributes from request
	childRequests.Entities.Add(childEntity);
}

pardon.RelatedEntities.Add(new Relationship(crmFieldName), childRequests);
Guid pardonId = cdsClient.Create(pardon);
```

This works when I run my automated test deserializing a JSON with the attributes for both entities. Now when I do the same in the Azure Function, using the exactly same JSON, I get the error above. How can the exact same input using the same code (I'm using the same library DLL in the automated test and Azure Function) calling the same CRM instance work once and cause an error on the server side the second time? 
Reproducible a 100%. It does not make any sense to me.

**Comment by zaha** [comment]
OK I found it: The role was lacking the Write permission for the parent entity, which makes sense since it has to add the child records after the parent is created. Issue solved, thanks for being my rubber duck! 👍

**Comment by MattB-msft** [comment]
Your not alone there... Testing with System Admin catches everyone from time to time :) 
Glad you found it.
