### ISSUE TITLE
client.Execute(new AddMemberListRequest() throwing Deserialize exception

### ISSUE THREAD

**Issue by pksorensen** [microsoft/PowerPlatform-CdsServiceClient#29]
The folllowing throws exception that it cant deserialize, but the action is carried out by CDS.
```
            client.Execute(new AddMemberListRequest()
            {
                EntityId = contact.Id,
                ListId = campaign.First().dca_telemarketinglist.Id
            });
```

```
The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult. The InnerException message was 'Error in line 1 position 371. Element 'http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult' contains data from a type that maps to the name 'http://schemas.microsoft.com/crm/2011/Contracts:AddMemberListResponse'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'AddMemberListResponse' and namespace 'http://schemas.microsoft.com/crm/2011/Contracts'.'.  Please see InnerException for more details.
```

```
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.PartInfo.ReadObject(XmlDictionaryReader reader, XmlObjectSerializer serializer)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.PartInfo.ReadObject(XmlDictionaryReader reader)
   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameterPart(XmlDictionaryReader reader, PartInfo part, Boolean isRequest)
```

**Comment by MattB-msft** [comment]
Thanks for your report @pksorensen,  could you provide a bit more on what you did or a repro of your project?   
The Message "AddMemberListRequest" is not directly included in the CdsServiceClient,   did you add the Dynamics Messages to your project? if so which nuget package?

**Comment by pksorensen** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>

    <UserSecretsId>25868fd8-9f86-493b-a39b-b2b384b38e5f</UserSecretsId>
    <GenerateCDSContext Condition="$(GenerateCDSContext) == ''">true</GenerateCDSContext>
    <CDSEnvironment>https://xxx.crm4.dynamics.com</CDSEnvironment>
    <CDSAuthType>OAuth</CDSAuthType>
    <CDSEntitiesToExport>listmember,list,campaign,contact,account,dca_calllistmember</CDSEntitiesToExport>
    <CDSSolutionsToExport>DXRM01Integrations</CDSSolutionsToExport>
    <CDSApplicationId>xxxx</CDSApplicationId>
    <CDSTenantId>xxx</CDSTenantId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Dynamics.Sdk.Messages" Version="0.2.8-Alpha" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
    <PackageReference Include="Microsoft.PowerPlatform.Cds.Client.Dynamics" Version="0.2.8-Alpha" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
    <PackageReference Include="DotNetDevOps.Extensions.PowerPlatform.MSBuild.CDSContext" Version="1.0.11" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>

```

```
#region Assembly Microsoft.Dynamics.Sdk.Messages, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\pks\.nuget\packages\microsoft.dynamics.sdk.messages\0.2.8-alpha\lib\netcoreapp3.1\Microsoft.Dynamics.Sdk.Messages.dll
#endregion

using Microsoft.Xrm.Sdk;
using System;
using System.Runtime.Serialization;

namespace Microsoft.Crm.Sdk.Messages
{
    [DataContract(Namespace = "http://schemas.microsoft.com/crm/2011/Contracts")]
    public sealed class AddMemberListRequest : OrganizationRequest
    {
        public AddMemberListRequest();

        public Guid ListId { get; set; }
        public Guid EntityId { get; set; }
    }
}
```

Platform is windows, rest should be given from above to snippets from the project.

**Comment by MattB-msft** [comment]
Thanks, 
will take a look

**Comment by MattB-msft** [comment]
@pksorensen We have identified the root issue here... and its not a "simple" fix.  We are working though solving this and will let you know when we have a fix.

**Comment by MattB-msft** [comment]
@pksorensen as an update,  we have the issue fixed now and are going though the publishing process. It required a fix in a few of our internal, not published, libs,  and thus takes a while to get though the process. 

Should be available and posted on Nuget in a day or so

**Comment by pksorensen** [comment]
thanks @MattB-msft :)
