### ISSUE TITLE
Update to create or update records when passing in an Entity Reference using Early Bound

### ISSUE THREAD

**Issue by schwoi** [microsoft/PowerPlatform-CdsServiceClient#39]
When trying to include an entity reference we get "Operation returned an invalid state code 'BadRequest'"

```
            var account = new Account
            {
                Name = "Create Test"
            };

            var accountId = svc.Create(account);

            var contact = new Contact
            {
                FirstName = "Create",
                LastName = "Test",
                ParentCustomerId = new EntityReference(Account.EntityLogicalName, accountId)
            };

            var contactId = svc.Create(contact);
```

Looking at the Last Error we get the following

************ HttpOperationException - POST contacts : Create To CDS via IOrganizationService |=> An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'parentcustomerid' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
Operation returned an invalid status code 'BadRequest'[TerminalFailure] Failed to Execute Command - POST contacts : RequestID=cfc6aec1-339c-4ca7-9f76-f3d4accb6119 : Create To CDS via IOrganizationService duration=00:00:00.0706016 ExceptionMessage = An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'parentcustomerid' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)

We worked out if we do the following it will work
```
            var account = new Account
            {
                Name = "Create Test"
            };
                
            var accountId = svc.Create(account);

            var contact = new Contact
            {
                FirstName = "Create",
                LastName = "Test",
            };
            contact["parentcustomerid_account"] = new EntityReference(Account.EntityLogicalName, accountId);

            var contactId = svc.Create(contact);
```

This doesn't seem to work when using custom attributes with entity references.

if we use
```
registration["htr_address1_stateid"] = new EntityReference(htr_State.EntityLogicalName, request.StateId);
```
It throws the same error as above
if we use the following
```
registration["htr_address1_stateid@odata.bind"] = new EntityReference(htr_State.EntityLogicalName, request.StateId);
```
the process no longer throws an error however it doesn't relate the record

**Comment by MattB-msft** [comment]
looking into this... 
thanks for the report.

**Comment by MattB-msft** [comment]
Problem found, we are working on a fix now..
The issue is specifically with Polymorphic lookup types.

**Comment by degville72** [comment]
I've seen Bad Request when using lookups specifically custom entities for example i have a lookup field when the specifying columns for a Retrieve it has to be lower case as I'd expect  "cb_incometype"  but if i use Update or Create the field must be "cb_IncomeType" or i get the bad request, is this the same issue or should i raise a new one?

**Comment by schwoi** [comment]
Thanks @MattB-msft I can confirm that the polymorphic lookups are now working as expected however the second part of the issue which @degville72 also mentioned is still an issue. I raised #42 and included a sample solution and code.
