### ISSUE TITLE
Message: ExecuteMultiple Request batch size exceeds the maximum batch size allowed!

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [microsoft/PowerPlatform-CdsServiceClient#64]
Hello,

Recently i get error when i send data to dynamics

10/14/2020 3:12:55 PM   |   UPSERT ERROR, type d'erreur : System.TimeoutException: The request channel timed out attempting to send after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
 ---> System.TimeoutException: The HTTP request to 'https://****************************.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.45.3122' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Execute(OrganizationRequest request)
   at VSMP_Contracts.CTR_Application.CreateMultiple(IOrganizationService _orgService, EntityCollection input) in 
10/14/2020 3:14:55 PM   |   UPSERT ERROR, type d'erreur : System.TimeoutException: The request channel timed out attempting to send after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
 ---> System.TimeoutException: The HTTP request to 'https://*****************************************/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.45.3122' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Execute(OrganizationRequest request)
   at VSMP_Contracts.CTR_Application.CreateMultiple(IOrganizationService _orgService, EntityCollection input) in 

Cordially

**Comment by BetimBeja** [comment]
Hello @HASSEN-MEDDEB-ATOS,
I see two different messages in your issue. In the stack trace you have posted I see the two minute execution time limit, which is not related to the sdk but is a limit in the system. Likewise the other error message you have as the title of the issue `ExecuteMultiple Request batch size exceeds the maximum batch size allowed!` is related to another limit in the system `ExecuteMultipleMaxBatchSize`, which typically is 1000 requests.

**Comment by MattB-msft** [comment]
With regards to overall timeout delays.. this is also configurable. 
Before creating the connection set this property:
**CdsServiceClient.MaxConnectionTimeout = (timespan)**
to configure the overall connection timeouts. 

this will be inherited by all connections created in your process.
