### ISSUE TITLE
NullReferenceException is thrown when WebAPI call fails

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#88]
Hi,

Repo steps:
1) Call cdsClient.Create(entity) with a non-existing attribute
2) The following exception is thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.PowerPlatform.Cds.Client.Utils.CdsClientOperationException.GenerateCdsClientOperationException(HttpOperationException httpOperationException)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.LogException(OrganizationRequest req, Exception ex, String errorStringCheck, String webUriMessageReq)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebExecuteAsync(String queryString, String body, HttpMethod method, Dictionary`2 customHeaders, String contentType, String errorStringCheck, Guid requestTrackingId)
--- End of inner exception stack trace ---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebAPIProcess_Execute(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsOrganizationRequestImpl(OrganizationRequest req, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Create(Entity entity)
```

Regards,
Stefan

**Comment by MattB-msft** [comment]
this bug has been addressed and will be in the next drop.
