### ISSUE TITLE
Cannot find a matching quote character for the character '''.

### ISSUE THREAD

**Issue by huyckst** [microsoft/PowerPlatform-CdsServiceClient#89]
Create record with datetime(dateonly) attribute 

Message: 
   Cannot find a matching quote character for the character '''.

Stacktrace:
```   
at System.DateTimeFormat.ParseQuoteString(ReadOnlySpan`1 format, Int32 pos, StringBuilder result)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset, StringBuilder result)
   at System.DateTimeFormat.FormatStringBuilder(DateTime dateTime, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider)
   at Microsoft.PowerPlatform.Cds.Client.Utilities.ToExpandoObject(String entityName, AttributeCollection entityAttributes, MetadataUtility mUtil)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.CdsCommand_WebAPIProcess_Execute(OrganizationRequest req, String logMessageTag, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.ExecuteCdsOrganizationRequestImpl(OrganizationRequest req, String logMessageTag, Boolean useWebAPI, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Create(Entity entity)
```

**Comment by chinhpham** [comment]
The error message and stack trace are not really helpful. Most of the time I have to capture the request and response via Fiddler to figure out the issue. I got same issue and I wrote the below extension to format the date (date only in my case) for querying via FetXml or WebApi. You might need to change it a bit to make it work for you.

`["somdate"] = someDate.ToCdsDate(queryOption)`

```
public static object ToCdsDate(this DateTime dateTime,
    CdsQueryOption queryOption = CdsQueryOption.ODataWebApi)
{
    return queryOption switch
    {
        CdsQueryOption.FetchXml => (object) dateTime.Date,
        _ => $"{dateTime:yyyy-MM-dd}"
    };
}
```

**Comment by ictgs1belu** [comment]
Thank for the feedback ! The issue does not occur when retrieving data but when creating a new record containing a dateonly attribute. 

I pretty sure the issue occurs in 

src/GeneralTools/CDSClient/Client/Utils/Utils.cs
Method -> ToExpandoObject

```dateTimeValue.ToUniversalTime().ToString("yyyy'-'MM'-'dd'");```

is should be

```dateTimeValue.ToUniversalTime().ToString("yyyy'-'MM'-'dd");```

TEST: [dotnetfiddle](https://dotnetfiddle.net/5hqznS)

**Comment by huyckst** [comment]
Thank for the feedback! The issue does not occur when retrieving data but when creating a new record containing a dateonly attribute.

I pretty sure the issue occurs in

src/GeneralTools/CDSClient/Client/Utils/Utils.cs
Method -> ToExpandoObject

```dateTimeValue.ToUniversalTime().ToString("yyyy'-'MM'-'dd'");```

is should be

```dateTimeValue.ToUniversalTime().ToString("yyyy'-'MM'-'dd");```

TEST: [dotnetfiddle](https://dotnetfiddle.net/iudhOk)
