### ISSUE TITLE
CdsTraceLogger.ResetLastError() - Index was out of range exception

### ISSUE THREAD

**Issue by chinhpham** [microsoft/PowerPlatform-CdsServiceClient#91]
Input: (2) batchId: default, (3) bypassPluginExecution: default

(1) FetchXml: (Works well with FetchXml Builder)

```
<fetch>
  <entity name="account" >
    <attribute name="accountid" />
    <attribute name="cs_id" />
    <filter>
      <condition attribute="cs_id" operator="eq" value="23983018" />
    </filter>
  </entity>
</fetch>
```

Stack trace:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at Microsoft.PowerPlatform.Cds.Client.CdsTraceLogger.ResetLastError()
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.GetEntityDataByFetchSearchEC(String fetchXml, Guid batchId, Boolean bypassPluginExecution)
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.GetEntityDataByFetchSearch(String fetchXml, Guid batchId, Boolean bypassPluginExecution)
```

**Comment by MattB-msft** [comment]
This error has been fixed in the next drop.
